spring:
  application:
    name: SSLCommerz-SpringBoot

sslcommerz:
  store-id: "ciphe650299504f174"
  store-password: "ciphe650299504f174@ssl"
  test-mode: true
  transaction:
    currency: "BDT"
    success-url: "http://localhost:8080/api/payment/success"
    fail-url: "http://localhost:8080/api/payment/fail"
    cancel-url: "http://localhost:8080/api/payment/cancel"
  api:
    base-url: "https://sandbox.sslcommerz.com" # Change this to the production URL when not in test mode
    initiate-transaction-path: "/gwprocess/v4/api.php"
    validation-path: "/validator/api/validationserverAPI.php"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
