spring:
  application:
    name: SSLCommerz-SpringBoot

sslcommerz:
  store-id: ${SSL_STORE_ID}
  store-password: ${SSL_STORE_PASSWORD}
  test-mode: true
  transaction:
    currency: "BDT"
    success-url: "http://localhost:8080/api/payment/success"
    fail-url: "http://localhost:8080/api/payment/fail"
    cancel-url: "http://localhost:8080/api/payment/cancel"
  api:
    sandbox:
      base-url: "https://sandbox.sslcommerz.com"
    production:
      base-url: "https://securepay.sslcommerz.com"
    initiate-transaction-path: "/gwprocess/v4/api.php"
    validate-transaction-path: "/validator/api/validationserverAPI.php"
    refund-transaction-path: "/validator/api/merchantTransIDvalidationAPI.php"
